[LUMI-169] - 💥 Basic front implementation
mozilla-ai/lumigator pull request #325
Opened 2024-10-30 10:50 UTC by george-mzai

## What's changing
Fetching , adding and deleting **datasets** through the UI

## How to test it

1.  `cd lumigator/frontend`
2.  `npm run dev`
3.  Go to localhost:3000 in your browser

2024-10-31 15:16 UTC, agpituk requested changes
.DS_Store was added to .gitignore but is still commited

2024-10-31 15:32 UTC, agpituk commented on lumigator/frontend/src/components/LDatasets.vue
> +const formatDate = (dateString) => {
can we use Intl for this instead of manually doing the format?

2024-10-31 15:35 UTC, veekaybee commented on lumigator/frontend/README.md
> +This directory contains the **frontend** code for the **Lumigator** project, built with **Vue 3**, and **Vite**. It is a modular and scalable front-end application designed to interact with the backe
```suggestion
This directory contains the **frontend** code for **Lumigator***, built with **Vue 3**, and **Vite**. It calls the FastAPI endpoints provided in `backend`.
```

2024-10-31 15:37 UTC, veekaybee commented on lumigator/frontend/README.md
> +### Visit `http://localhost:3000` in your browser. The application runs at this addrees by default.
```suggestion
Visit `http://localhost:3000` in your browser. The application runs at this address by default.
```

2024-10-31 15:37 UTC, veekaybee commented on lumigator/frontend/README.md
> +VITE_API_URL=http://localhost:8000/api  # Backend API URL
does this respect/resolve the API version number?

2024-10-31 15:38 UTC, veekaybee commented on lumigator/frontend/README.md
> +Contributions are welcome! Please follow these steps:
Let's link to our current contributor guide here instead https://github.com/mozilla-ai/lumigator/blob/main/CONTRIBUTING.md

2024-10-31 15:38 UTC, veekaybee commented on lumigator/frontend/README.md
> +### License
No need to mention the license here as it's at the root of the repo

2024-10-31 15:41 UTC, veekaybee commented on lumigator/frontend/src/components/LUpload.vue
> +/* Add your styles here */
still need this comment?

2024-10-31 15:41 UTC, veekaybee commented on lumigator/frontend/vite.config.js
> +    host: 'localhost', // Specify the host
don't need this comment

2024-10-31 15:41 UTC, veekaybee commented on lumigator/frontend/vite.config.js
> +    port: 3000,        // Specify the port
don't need this comment

2024-10-31 15:42 UTC, veekaybee commented on lumigator/python/mzai/backend/backend/main.py
> +        allow_origins=origins,  # Adjust this list as needed for security (e.g., ["http://localhost:3000"])
can remove this comment

2024-11-04 23:10 UTC, george-mzai commented on lumigator/frontend/src/App.vue
> +const getDatasets = async () => {
Yes it will. This branch is a PoC only for the chosen stack. An implementation aligned with this suggestion (and the entire FE architecture) is in the making on the [` test_primevue`](https://github.com/mozilla-ai/lumigator/tree/test_primevue) branch.

2024-11-07 19:30 UTC, closed without merging