Replace localstack with minio
mozilla-ai/lumigator pull request #491
Opened 2024-12-11 10:12 UTC by javiermtorres

# What's changing

The localstack service is replaced with minio for local deployments.

Closes https://github.com/mozilla-ai/lumigator/issues/487

# How to test it

Start lumigator (e.g. using `make local-up`) and check that minio starts instead of localstack.

All automated tests should work as usual.

# Additional notes for reviewers

N/A

# I already...

- [x] Tested the changes in a working environment to ensure they work as expected
- [ ] Added some tests for any new functionality
- [ ] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [x] Checked if a (backend) DB migration step was required and included it if required
  - No DB update is needed.

2024-12-11 22:38 UTC, javiermtorres commented
One issue I found is that, if the .env.example is modified, then the integration tests should also be run, just in case the env vars are no longer valid. I can make a follow up PR to amend that.

Also, I didn't notice a clear indication that the .env would be generated from the .env.example and used within the docker-compose. If such indication is indeed present, could anyone please point me to it? @agpituk maybe? Thanks in advance.

2024-12-13 14:07 UTC, aittalam commented
> Also, I didn't notice a clear indication that the .env would be generated from the .env.example and used within the docker-compose. If such indication is indeed present, could anyone please point me to it? @agpituk maybe? Thanks in advance.

Not sure if it is in the documentation, but you can find it in the Makefile:

```
.env:
    @if [ ! -f .env ]; then cp .env.example .env; echo ".env created from .env.example"; fi
```

2024-12-13 14:22 UTC, aittalam commented on docker-compose.yaml
> +    image: quay.io/minio/minio # TODO add version
+1 on relying on a specific version!

2024-12-13 14:43 UTC, aittalam commented on docker-compose.yaml
> +          curl --create-dirs -o /etc/lumigator/minio/mc https://dl.min.io/client/mc/release/linux-amd64/mc
Using a generic container where we need to install the minio client requires us to install `curl` and run `apt update` first, the result is that it takes more than one minute to pull the whole system up. Another linked issue is that whenever there's an issue with `apt-get` we cannot start lumigator. This happened while testing:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/d64a0ba4-0798-4faa-9bb5-7f8351566f50" />

As an alternative we could have something like:
```
 minio-admin:
    image: quay.io/minio/minio
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - /bin/bash
    command:
      - -c
      - |
          set -ex
          ...
```

The minio image is already cached anyway, the load time decreases to ~35 sec, and we do not have to reinstall stuff at every run. WDYT?

A follow up question: is there any way to persist the minio configuration so we can pick it up if available and run the following only if that is not already set?

2024-12-13 14:44 UTC, aittalam commented on lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py
> +    # dummy change
Great idea to have CI run! Just a heads up to remove it before merge  ;-)

2024-12-13 14:56 UTC, aittalam requested changes
Thanks a lot for the PR @javiermtorres, I think this is great! I tested this and it runs for me (I had a few issues at first, mostly due to old env vars being present and the `.env`/`.env.example` thing going on, but afterwards things just ran fine). Accessing all persisted data via Web UI is very cool too :-)

Can I ask you to please go through our sources and look for `4566` and `localstack` too? I think there are few other spots we might need to update contextually to this change such as:

- `.env`
- documentation (README.md, installation.md, dev.md, etc)

re: `conftest.py`, I see we are still using localstack. Do you see the need to move tests to minio too? IMHO it is not something urgent, but testing on the same stack we are running makes a bit more sense (and reduces the amount of dependencies + lumigator's fingerprint)

2024-12-15 12:43 UTC, javiermtorres commented
@aittalam thanks for trying out the PR and checking that it works :) I'll address the concerns first thing on Monday.
Re: the dependence on localstack for tests.... It's being addressed in #453 , but unfortunately there's _one single test case_ that is inexplicably failing; I cannot even get meaningful logs from Ray. I know that it somehow has to do with inference, but I can't see how. I'll try rebasing to main, but it should be up to date. If something there rings a bell, _please please_ let me know :D

Once that other PR is in place, we'll remove any dependency on localstack in source and tests.

2024-12-16 06:01 UTC, aittalam commented
> @aittalam thanks for trying out the PR and checking that it works :) I'll address the concerns first thing on Monday. Re: the dependence on localstack for tests.... It's being addressed in #453 , but unfortunately there's _one single test case_ that is inexplicably failing; I cannot even get meaningful logs from Ray. I know that it somehow has to do with inference, but I can't see how. I'll try rebasing to main, but it should be up to date. If something there rings a bell, _please please_ let me know :D
> 
> Once that other PR is in place, we'll remove any dependency on localstack in source and tests.

That's great @javiermtorres , many thanks!
I'll check https://github.com/mozilla-ai/lumigator/pull/453 today and see if I can be of any help there.

2024-12-16 13:55 UTC, veekaybee commented on .env.example
> +AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-http://localhost:9000}
let's leave a comment about why this is `9000`

2025-01-09 08:21 UTC, javiermtorres commented
> > Also, I didn't notice a clear indication that the .env would be generated from the .env.example and used within the docker-compose. If such indication is indeed present, could anyone please point me to it? @agpituk maybe? Thanks in advance.
> 
> Not sure if it is in the documentation, but you can find it in the Makefile:
> 
> ```
> .env:
>     @if [ ! -f .env ]; then cp .env.example .env; echo ".env created from .env.example"; fi
> ```

It won't hurt to add some comment in some README to warn that the `.env` is included in the Makefile. I'll check it out.

2025-01-09 08:33 UTC, javiermtorres commented on docker-compose.yaml
> +    image: quay.io/minio/minio # TODO add version
Choosing RELEASE.2024-12-18T13-15-44Z as the latest non-new-feature release. Since semver is not used I cannot easily check sets of features or backward compatibility :-/ Let me know if anything breaks with this.

2025-01-09 08:35 UTC, javiermtorres commented on docker-compose.yaml
> +          curl --create-dirs -o /etc/lumigator/minio/mc https://dl.min.io/client/mc/release/linux-amd64/mc
> The minio image is already cached anyway, the load time decreases to ~35 sec, and we do not have to reinstall stuff at every run. WDYT?

If you tried it out and it worked, fine for me. I don't think the container size will be an issue. I didn't use it at first because one needs to install the minio client anyway (it's not bundled with minio itself afaict), but it definitely helps to use a cached image.

2025-01-09 08:37 UTC, javiermtorres commented on docker-compose.yaml
> +          curl --create-dirs -o /etc/lumigator/minio/mc https://dl.min.io/client/mc/release/linux-amd64/mc
> A follow up question: is there any way to persist the minio configuration so we can pick it up if available and run the following only if that is not already set?

Hm. Good question. If the commands are idempotent it doesn't matter (so buckets are not recreated anew if they already exist, etc etc). Was there something specific that failed in your setup?

2025-01-09 08:37 UTC, javiermtorres commented on lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py
> +    # dummy change
Wops sorry :-S

2025-01-14 10:31 UTC, javiermtorres commented on docker-compose.yaml
> +          curl --create-dirs -o /etc/lumigator/minio/mc https://dl.min.io/client/mc/release/linux-amd64/mc
Resolving this issue. I followed your suggestion and reused the minio image, it does indeed contain the mc admin commands. Shame on me 👎

2025-01-14 10:32 UTC, javiermtorres commented
> > A follow up question: is there any way to persist the minio configuration so we can pick it up if available and run the following only if that is not already set?
> 
> Hm. Good question. If the commands are idempotent it doesn't matter (so buckets are not recreated anew if they already exist, etc etc). Was there something specific that failed in your setup?

Leaving the notes on minio persistence here for a future issue, since the original comment is resolved.

2025-01-14 18:35 UTC, aittalam approved these changes
LGTM, thank you!
I saw the branch got out-to-date wrt main, I pre-approve this so you'll be able to land this after merging from main.

2025-01-14 18:43 UTC, javiermtorres commented
Thanks a lot @aittalam :)

2025-01-15 09:08 UTC, agpituk approved these changes

2025-01-15 15:58 UTC, merged